### PR TITLE
Fixed bug in Shared Overlays. Added manual save to recipe editor

### PR DESCRIPTION
**Pull request by Jaimi**
Shared Overlays were not working due to an issue with the recipe editor. There were actually two issues - one in a loop that didn't work when there were only 2 slots. Another with the Set function for the overlays reusing the list. (This was a bugfix for the cutout code).

### CODE REVIEW

**Comment by kenamis** [comment]
in characterBaseEditor line 664

[code]
                    int CurrentHash = CurrentOverlays.GetHashCode();
                    int PreviousHash = PreviousOverlays.GetHashCode();
[/code]

I get a warning that these are unused.  Did you have a plan for them?

**Comment by Jaimi** [comment]
Debugging code only - they can be safely deleted. I left in the hash
information on the slotdata on purpose though

**Comment by kenamis** [comment]
//_needsUpdate = PreInspectorGUI(); //<--I think this is wrong
                /*if (PreInspectorGUI())
                {
                    _needsUpdate = true;
                }*/
                _needsUpdate |= PreInspectorGUI();//<--Change to this style?

                _needsUpdate |= ToolbarGUI();
				/*if (ToolbarGUI())
				{
					_needsUpdate = true;
				}*/

                _needsUpdate |= PostInspectorGUI();
				/*if (PostInspectorGUI())
				{
					_needsUpdate = true;
				}*/

                /*if (_AutomaticUpdates == false) //<-- I think this eats the needUpdate flag if someone else wants to use it.
                {
                    _needsUpdate = false;
                }*/

                if ((_AutomaticUpdates && _needsUpdate) || _forceUpdate) //<--Put the check for AutomaticUpdate here so that the needsUpdate flag isn't eaten?
				{
					DoUpdate();
                    _needsUpdate = false;
                    _forceUpdate = false;
				}`

**Comment by ecurtz** [comment]
That's a lot of different flags for what seems like a pretty simple test.

You do need to either initialize _needsUpdate to false or do the current version where it's set to the first result.

I agree that the |= version is tidier, but the result is identical.

**Comment by Jaimi** [comment]
I personally dislike shortcut code like the |=, and had to fix several
errors in the recipe editor that had used that pattern. Don't ask me to
recall exactly, as it was over a year ago.  I see where you are going with
the _needsupdatr -- tracking if any changes happened since the last save
for the warning and clearing it on save. This will mean you need'll need to
set it to false in the selectionchanged instead of at the top of the loop.

**Comment by kenamis** [comment]
@jaimi - Yea, I lean towards disliking that shortcut code too, I just thought I'd suggest it since mono was suggesting it.

@ecurtz isn't needing to initialize _needsUpdate in that function the old logic, it won't work if we want to have pending changes hanging around and DoUpdate later from a save button or losing focus, correct?

Last night, I got the selection event working but I'm checking _needsUpdate for true to show a dialog to the user to save, but _needsUpdate is always false.  I'm still trying to figure out why.

**Pull request merged**
