### PR TITLE
Add TPoses to be used with Mecanim animations

### PR DESCRIPTION
**Pull request by mysticfall**
* Add Mecanim avatar configuration for human models.
 * Provide Mecanim compatible TPose assets.

### CODE REVIEW

**Comment by kenamis** [comment]
@mysticfall what version of unity did you use to configure the avatar and extract the tpose?

**Comment by mysticfall** [comment]
I think it was `2017.1.x` and now I'm using `2017.3b`.

**Comment by Jaimi** [comment]
MysticFall - can you include the old tpose assets also (rename them with "_legacy" at the end perhaps?

**Comment by mysticfall** [comment]
@Jaimi I didn't replace or change anything that I thought might cause a compatibility problem (but please check if it's really the case before merging).

The T-pose files (with `_Mecanim` suffix) are new additions and I didn't changed the race data to use these files instead of the old ones. Do you mean I can change them also, as long as I keep the old T-pose files?

And the changed meta files of FBX models contain avatar configuration settings for the new T-poses, which I believe was absent previously, so I didn't think it would cause problems for other people.

**Comment by Jaimi** [comment]
Oh, OK - sorry about that, it's hard to tell sometimes with the way the pull request works. No need to change anything!

**Comment by mysticfall** [comment]
Please don't worry. I'm just glad that I didn't screw up something :smile:

**Comment by virror** [comment]
@Jaimi @mysticfall So we should not make the new one default then? Then what is the use of including this,i doubt ppl will notice and use it if its not default?

**Comment by Jaimi** [comment]
It definitely has value to include it (I'll be using it myself). But not
sure about making it the default, because it has the potential to cause
people to re-adjust their animations again.

**Comment by virror** [comment]
Hmm, ok. I just assume that 99% of the users have no idea thet you can even change t-pose file. Maybe we can switch this with 3.0 then.

**Pull request merged**
