### PR TITLE
Remove physics from SimpleSetup.

### PR DESCRIPTION
**Pull request by Jaimi**
Added to BoneyTail recipe, and added physics layer initialization at the start just to be sure it was setup as well.

### CODE REVIEW

**Comment by kenamis** [comment]
can you remove the physics recipe from the dca prefab too?  I'd do it but I have a bunch of unsaved changes in the renderer management branch.

**Comment by kenamis** [comment]
I was just looking at it too.  It looks like the DCA in the simple scene has been detached from the prefab, but the DCA in the simple scene does have that physics recipe in it's additional recipes.

**Comment by Jaimi** [comment]
Yeah - I removed it from the DCA in the scene. It will get added back as part of the boneytail recipe, which will also setup the physics matrix (if anyone uses it).

**Comment by Jaimi** [comment]
But I just noticed I didn't include the scene file. <groan> Let me get that checked in.

**Pull request merged**
