### PR TITLE
Update UmaRaceUpdaterWindow.cs

### PR DESCRIPTION
**Pull request by twobob**
Fixed up PULL request

### CODE REVIEW

**Comment by kenamis** [comment]
thanks! looks a lot better.  FYI, in the future you can commit to the same branch the PR is pulling from and the PR will auto-update if it hasn't been merged yet, so you don't need to cancel the old one and create a new one.

**Comment by kenamis** [comment]
I don't think you need to convert the returned overlay list to an array to iterate over it, do you?  If not, that's going to unnecessarily create garbage.

**Comment by kenamis** [comment]
true, it's an editor script and not performance critical, but it's still a managed environment and if you don't need to create a new array when you can reference the original list, then why not? right? sorry to be picky

**Comment by twobob** [comment]
it's a foreach. 
shall I got for just a for next loop then.

**Comment by kenamis** [comment]
you can use a foreach loop, you just don't need the ".ToArray()".  A foreach loop can be used on a List collection which is what GetOverlayList() returns.  ".ToArray()" copies the list elements to an array which is the unnecessary memory allocation and garbage in this case.  Make sense?

**Comment by twobob** [comment]
#137

**Comment by twobob** [comment]
"thanks! looks a lot better. FYI, in the future you can commit to the same branch the PR is pulling from and the PR will auto-update if it hasn't been merged yet, so you don't need to cancel the old one and create a new one."

Fair enough. I'll look at that next time. Funky web editing atm

**Pull request closed without merging**
