### PR TITLE
BoneyTail (physics ponytail), Editor additions

### PR DESCRIPTION
**Pull request by Jaimi**
Editor Additions (shows what the type is when in list mode)
Ponytail physics example (additional skeletal bones)
No extra scene - just look in one of the existing DCS scenes - it's a regular recipe.

Not sure why it updated all the materials below. But since 5.6.4 is the minimum version (and that's what I used), seemed appropriate to check them in.

### CODE REVIEW

**Comment by kenamis** [comment]
you have a file named "new UMAWardroberecipe" in male_tallshoes

**Comment by kenamis** [comment]
is UMAIndex.png a new icon?

**Comment by Jaimi** [comment]
Thanks, I'll remove the blank recipe. UMAIndex.png is a new icon (displays with the indexed type, if the item is in the index)

**Comment by Jaimi** [comment]
Blank recipe removed.

**Pull request merged**
